Format clean ZFS dataset code
Signed-off-by: DaRK AnGeL <28630321+masterwishx@users.noreply.github.com>

diff --git a/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover b/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
--- a/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
+++ b/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
@@ -1138,28 +1138,28 @@ processTheMoves () {
             # Clean parent ZFS dataset if empty
             if [[ "$ACTION" =~ "move" ]] && [ $TESTMODE = "no" ] && [ $CLEANDATASETS = "yes" ]; then
                 if is_zfs_mountpoint_fstype "/mnt/$PRIMARYSTORAGENAME"; then
-                        DATASET="${PRIMARYSTORAGENAME}/${SHARENAME}"
-                        echo "Checking if ZFS dataset ${DATASET} is completely empty..."
-                        
-                        # Check for any files in the ZFS dataset avalible
-                        dataset_file_count=$(find "/mnt/${DATASET}" -type f | wc -l)
-                        if [ "${dataset_file_count}" -eq 0 ]; then
-                        echo "ZFS dataset ${DATASET} appears empty, attempting to unmount and delete..."
-                            zfs unmount "${DATASET}"
-                            if [ $? -ne 0 ]; then
-                               echo "Failed to unmount ZFS dataset: ${DATASET}"
-                            else 
-                               echo "ZFS dataset ${DATASET} has been successfully unmounted."
-                            fi
-                            zfs destroy -r "${DATASET}"
-                            if [ $? -ne 0 ]; then
-                              echo "Failed to destroy ZFS dataset: ${DATASET}"
-                            else
-                              echo "ZFS dataset ${DATASET} has been successfully destroyed."
-                            fi            
+                    DATASET="${PRIMARYSTORAGENAME}/${SHARENAME}"
+                    echo "Checking if ZFS dataset ${DATASET} is completely empty..."
+                    
+                    # Check for any files in the ZFS dataset avalible
+                    dataset_file_count=$(find "/mnt/${DATASET}" -type f | wc -l)
+                    if [ "${dataset_file_count}" -eq 0 ]; then
+                    echo "ZFS dataset ${DATASET} appears empty, attempting to unmount and delete..."
+                        zfs unmount "${DATASET}"
+                        if [ $? -ne 0 ]; then
+                            echo "Failed to unmount ZFS dataset: ${DATASET}"
+                        else 
+                            echo "ZFS dataset ${DATASET} has been successfully unmounted."
+                        fi
+                        zfs destroy -r "${DATASET}"
+                        if [ $? -ne 0 ]; then
+                            echo "Failed to destroy ZFS dataset: ${DATASET}"
                         else
-                            echo "ZFS dataset ${DATASET} contains files or directories, will not delete..."
-                        fi                    
+                            echo "ZFS dataset ${DATASET} has been successfully destroyed."
+                        fi            
+                    else
+                        echo "ZFS dataset ${DATASET} contains files or directories, will not delete..."
+                    fi                    
                 fi
             fi            
 
