original mover: ensure source for -e options is a mounted array disk
Signed-off-by: DaRK AnGeL <28630321+masterwishx@users.noreply.github.com>

diff --git a/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover b/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
--- a/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
+++ b/source/ca.mover.tuning/usr/local/emhttp/plugins/ca.mover.tuning/age_mover
@@ -1696,11 +1696,6 @@ reset() {
 empty() {
     DISK="$1"
 
-    if [ ! -d "/mnt/$DISK" ]; then
-        echo "Error: disk '$DISK' not found"
-        exit 1
-    fi
-
     if [ -f $PIDFILE ]; then
         if ps h $(cat $PIDFILE) | grep mover; then
             echo "mover: already running"
@@ -1774,7 +1769,7 @@ usage() {
     echo ""
     echo "Usage: $0 start [-e <disk_name>]"
     echo "       $0 stop|softstop|status|reset"
-    echo "       <disk_name> must match pattern 'disk[0-9]*'"
+    echo "       <disk_name> must match pattern 'disk[0-9]*' and /mnt/<disk_name> must be a mountpoint"
     echo ""
     echo "reset  - reset config file to default values and delete override config folder"
     exit 1
@@ -1783,7 +1778,11 @@ usage() {
 # validate disk name
 validate_disk() {
     if [[ ! "$1" =~ ^disk[0-9]+$ ]]; then
-        echo "Error: <disk_name> must match pattern 'disk[0-9]*'"
+        echo "Error: <disk_name> must match pattern 'disk[0-9]+$'"
+        usage
+    fi
+    if ! mountpoint --nofollow /mnt/$1 >/dev/null 2>&1; then
+        echo "Error: nothing mounted at /mnt/$1"
         usage
     fi
 }
